### ISSUE TITLE
run as terminal script as well? 

### ISSUE THREAD

**Issue by alisonmyers** [saud-learning-services/canvas-batch-change-dates#10]
Is it possible for this one to be set up to run as a terminal script with appropriate inputs? 
(Or, is Jupyter notebook too chunked for this to make sense?).

**Comment by markoprodanovic** [comment]
I'll give it a try!

**Comment by markoprodanovic** [comment]
We'd need a way to get tokens without using Jupyter. Use `.env` when running with terminal?

**Comment by alisonmyers** [comment]
define main function that asks for input? 

if __name__ == "__main__":
    # execute only if run as a script
    main()
